# Generated by Django 5.2.1 on 2025-08-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
